name: php-cs-fixer

on:
  push:
    paths:
      - '**.php'
      - '.php-cs-fixer.dist.php'
      - '.github/workflows/php-cs-fixer.yml'
  pull_request:
    paths:
      - '**.php'
      - '.php-cs-fixer.dist.php'
      - '.github/workflows/php-cs-fixer.yml'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHP-CS-Fixer (dry run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
